### ISSUE TITLE
Removed ? in rewrite rules causes duplicate query parameters

### ISSUE THREAD

**Issue by 125m125** [prerender/prerender-nginx#2]
The commit 8c5e3d300a4de7fe32c2da394f10c2d453351537 removed the question marks from the rewrite rules. Without the ? at the end, nginx seems to duplicate the query parameters: `/?a=b` gets proxied as `/?a=b&a=b` to prerender.io. See https://stackoverflow.com/a/28597652 or https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite .

Can I just readd the `?` in my config or will this cause other issues?

**Comment by lluczo** [comment]
Good finding, thank you, I added the ? to the rewrite rules.
