### ISSUE TITLE
Wrong new Google crawler

### ISSUE THREAD

**Issue by Vitalick** [prerender/prerender-nginx#4]
New Google crawler it is `~*google-inspectiontool`, not `~*googlebot-inspectiontool`. 

https://github.com/prerender/prerender-nginx/blob/fc3adca6e5fcd707243a5801766fe3ce607d0c46/nginx-reverse-proxy/nginx.conf#L51

**Comment by lluczo** [comment]
thank you, fixed in https://github.com/prerender/prerender-nginx/pull/6
